### ISSUE TITLE
Doc Strings are not handled

### ISSUE THREAD

**Issue by michalkaftanski-airhelp** [allure-framework/allure-cucumber#68]
Consider this as a bug: when scenario has some _Doc Strings_ within there is:
```
undefined method `[]' for nil:NilClass (NoMethodError)
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/allure-ruby-adaptor-api-0.7.1/lib/allure-ruby-adaptor-api/builder.rb:100:in `add_attachment'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/allure-cucumber-0.6.1/lib/allure-cucumber/dsl.rb:9:in `attach_file'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:208:in `attach_multiline_arg_to_file'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:153:in `before_multiline_arg'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/ast.rb:347:in `accept'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/ast.rb:115:in `accept'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:580:in `step_invocation'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:543:in `step_invocation'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:387:in `print_step'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:251:in `after_test_step'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:107:in `after_test_step'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/formatter/legacy_api/adapter.rb:31:in `block in initialize'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `block in broadcast'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `each'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:34:in `broadcast'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/event_bus.rb:40:in `method_missing'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:35:in `around_hook'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:120:in `block (2 levels) in compose_around_hooks'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:121:in `compose_around_hooks'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:26:in `block in describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:57:in `test_case'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/retry.rb:18:in `test_case'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/quit.rb:12:in `test_case'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/case.rb:25:in `describe_to'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/filter.rb:62:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/compiler.rb:24:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core/gherkin/parser.rb:37:in `done'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:32:in `parse'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-core-3.1.0/lib/cucumber/core.rb:21:in `compile'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/runtime.rb:75:in `run!'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/lib/cucumber/cli/main.rb:34:in `execute!'
/Users/michalkaftanski/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/cucumber-3.1.1/bin/cucumber:9:in `<top (required)>'
/Users/michalkaftanski/.rbenv/versions/2.4.4/bin/cucumber:23:in `load'
/Users/michalkaftanski/.rbenv/versions/2.4.4/bin/cucumber:23:in `<main>'
```

Environment:
Ruby 2.4.4
latest gems: (cucumber (3.1.1), cucumber-core (3.1.0), allure-cucumber (0.6.1), allure-ruby-adaptor-api (0.7.1)

**Comment by andrejska** [comment]
Same issue is with data tables, have tried all cucumber versions starting from 3.0.0, non of them works

I would consider this as top priority bug

**Comment by andrejska** [comment]
@michalkaftanski-airhelp 
Fixed my issue, should fix yours as well, please try:
```
  gem 'allure-cucumber', branch: 'master', git: 'https://github.com/andrejska/allure-cucumber'
  gem 'allure-ruby-adaptor-api', branch: 'master', git: 'https://github.com/andrejska/allure-ruby-commons'
```
