### ISSUE TITLE
File name too long @ rb_sysopen

### ISSUE THREAD

**Issue by serhatbolsu** [allure-framework/allure-cucumber#76]
I am using `allure-cucumber (0.6.1)` 

Getting this error
```
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:162:in `initialize'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:162:in `open'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/allure-cucumber-0.6.1/lib/allure-cucumber/formatter.rb:162:in `embed'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/ignore_missing_messages.rb:11:in `method_missing'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:220:in `send_to_formatter'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:85:in `block in send_output_to'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:85:in `each'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:85:in `send_output_to'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:45:in `block in send_output_to'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:45:in `each'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/ast.rb:45:in `send_output_to'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:858:in `after'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:791:in `after_test_case'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:727:in `after_test_case'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:626:in `after_test_case'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:272:in `after_test_case'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:111:in `after_test_case'
/Users/serhat/.rvm/gems/ruby-2.5.1/gems/cucumber-3.1.2/lib/cucumber/formatter/legacy_api/adapter.rb:37:in `block in initialize'
...
```

Spotted from the code:
`src` is passed as filename argument
[https://github.com/allure-framework/allure-cucumber/blob/master/lib/allure-cucumber/formatter.rb#L162](url)

**Comment by serhatbolsu** [comment]
Figured this is happening while the file is empty or not created.

**Comment by eandersonEverfi** [comment]
@serhatbolsu I am having this exact same issue as you describe when I have a cucumber feature test fail. (When I do not have any failures I am able to create an allure report without issue). How did you resolve the error?
I see that you figured out that the file is empty or not created was the source of the issue. Can you provide details on what you added to your code to resolve/account for this error?
Thank you for your help.

**Comment by serhatbolsu** [comment]
Hi @eandersonEverfi  I dont really remember. 
Maybe its something to do with report file path ? you can try to create the "dir" before
Also I am using a custom library now;
```
gem "allure-cucumber", :git => 'https://github.com/serhatbolsu/allure-cucumber.git', :branch => 'master'
gem "allure-ruby-adaptor-api", :git => 'https://github.com/serhatbolsu/allure-ruby-commons.git', :branch => 'master'
```

**Comment by eandersonEverfi** [comment]
Hey @serhatbolsu 
Thank you for your assistance.
I like your work on the custom lib and the additional methods for the allure-cucumber api.
