### ISSUE TITLE
Empty reports are getting generated at the end of the suite

### ISSUE THREAD

**Issue by sureshpathipati** [allure-framework/allure-cucumber#79]
I have triggered a build with one feature(Around 10 scenarios). At the end of the build before triggering report it failing with the following issue.

stack trace:
-------------
undefined method `[]' for nil:NilClass (NoMethodError)
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/allure-ruby-adaptor-api-0.6.10/lib/allure-ruby-adaptor-api/builder.rb:45:in `stop_test'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/allure-cucumber-0.5.8/lib/allure-cucumber/formatter.rb:229:in `stop_test'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/allure-cucumber-0.5.8/lib/allure-cucumber/formatter.rb:83:in `after_scenario'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/allure-cucumber-0.5.8/lib/allure-cucumber/formatter.rb:87:in `after_feature_element'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/ignore_missing_messages.rb:10:in `method_missing'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:548:in `after'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:540:in `after_test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:260:in `after_test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:99:in `after_test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/legacy_api/adapter.rb:43:in `after_test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:16:in `block in method_missing'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `each'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/formatter/fanout.rb:15:in `method_missing'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/runner.rb:19:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/apply_around_hooks.rb:8:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_hooks.rb:5:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/apply_before_hooks.rb:5:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/apply_after_step_hooks.rb:8:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/activate_steps.rb:11:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/case.rb:23:in `describe_to'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:17:in `block in done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `each'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/locations_filter.rb:16:in `done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/filter.rb:61:in `done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/compiler.rb:23:in `done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core/gherkin/parser.rb:35:in `done'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:29:in `parse'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-core-1.5.0/lib/cucumber/core.rb:18:in `compile'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:67:in `run!'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/bin/cucumber:23:in `load'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/bin/cucumber:23:in `<main>'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:24:in `eval'
/var/jenkins_home/.rvm/gems/ruby-2.1.4/bin/ruby_executable_hooks:24:in `<main>'

**Comment by sureshpathipati** [comment]
My bad. I have scenario without any steps
Hence failing. 

Thanks
